name: CI Pipeline for python pytest

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: checkout repo
        uses: actions/checkout@v4

      - name: install dependency
        run: pip install -r requirements.txt

      - name: run test
        run: pytest
